# Generated by Django 5.2.7 on 2025-10-19 14:10

import account.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="A unique UUID identifier for the token.",
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the token was created.",
                    ),
                ),
                (
                    "revoked",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the token has been revoked (blacklisted).",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=account.models.default_expiry,
                        help_text="Expiration date and time for the token (default 7 days from creation).",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user associated with this refresh token.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refresh_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
