# Generated by Django 5.2.7 on 2025-10-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_refreshtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
